In [ ]:
#import Numpy library
import numpy as np

In [ ]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4])

In [ ]:
#print first array
print(first_numpy_array)

In [ ]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

In [ ]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

In [ ]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

In [ ]:
#array with arange method
array_with_arange = np.arange(12)
array_with_arange


In [ ]:
#array with reshape method  
array_with_reshape = array_with_arange.reshape(3,4)
array_with_reshape

In [ ]:
#array with linspace method
array_with_linspace = np.linspace(1,10,20)
array_with_linspace

In [ ]:
#one dimensional array
one_dimensional_array = np.arange(15)
one_dimensional_array

In [ ]:
#two dimensional array
two_dimensional_array = one_dimensional_array.reshape(3,5)
two_dimensional_array

In [ ]:
#three dimensional array
three_dimensional_array = np.arange(27).reshape(3,3,3)
three_dimensional_array

Creating Multiple Dimensional Arrays

In [ ]:
np.array(24)

In [ ]:
three_dimensional_array.shape

In [ ]:
three_dimensional_array.ndim

converting a 1d array to 2d array or 3d array

In [16]:
#creating a 1d array
numpy_arr = np.array([x for x in range(1,10)])
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#converting a 1d array to 2d array
numpy_arr_2d = numpy_arr.reshape(3,3)
numpy_arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
#converting a 1d array to 3d array
numpy_arr = np.array([x for x in range(1,13)])

In [24]:
numpy_arr_3d = numpy_arr.reshape(3,2,2)
numpy_arr_3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [26]:
#flatten method
numpy_arr_3d.reshape(-1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

conditional logic in numpyu arrays

In [27]:
x = np.array([x for x in range(1,10)])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.where(x%2==0,'even','odd')

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd'],
      dtype='<U4')

In [29]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [30]:
np.select(condlist,choicelist,default=x)

array([  1,   4,   9,  16,   5, 216, 343, 512, 729])

indexing and slicing

In [32]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [34]:
array_1d[-3]

4

In [37]:
array_2d[1,2]

6