In [12]:
#import Numpy library
import numpy as np

In [13]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4])

In [14]:
#print first array
print(first_numpy_array)

[1 2 3 4]


In [15]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#array with arange method
