In [2]:
#import Numpy library
import numpy as np

In [3]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4])

In [4]:
#print first array
print(first_numpy_array)

[1 2 3 4]


In [5]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#array with arange method
array_with_arange = np.arange(12)
array_with_arange


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
#array with reshape method  
array_with_reshape = array_with_arange.reshape(3,4)
array_with_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
#array with linspace method
array_with_linspace = np.linspace(1,10,20)
array_with_linspace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
#one dimensional array
one_dimensional_array = np.arange(15)
one_dimensional_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
#two dimensional array
two_dimensional_array = one_dimensional_array.reshape(3,5)
two_dimensional_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
#three dimensional array
three_dimensional_array = np.arange(27).reshape(3,3,3)
three_dimensional_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])