In [2]:
#import Numpy library
import numpy as np

In [3]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4])

In [4]:
#print first array
print(first_numpy_array)

[1 2 3 4]


In [5]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#array with arange method
array_with_arange = np.arange(12)
array_with_arange


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
#array with reshape method  
array_with_reshape = array_with_arange.reshape(3,4)
array_with_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
#array with linspace method
array_with_linspace = np.linspace(1,10,20)
array_with_linspace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [11]:
#one dimensional array
one_dimensional_array = np.arange(15)
one_dimensional_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
#two dimensional array
two_dimensional_array = one_dimensional_array.reshape(3,5)
two_dimensional_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
#three dimensional array
three_dimensional_array = np.arange(27).reshape(3,3,3)
three_dimensional_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Creating Multiple Dimensional Arrays

In [14]:
np.array(24)

array(24)

In [15]:
three_dimensional_array.shape

(3, 3, 3)

In [16]:
three_dimensional_array.ndim

3

converting a 1d array to 2d array or 3d array

In [17]:
#creating a 1d array
numpy_arr = np.array([x for x in range(1,10)])
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#converting a 1d array to 2d array
numpy_arr_2d = numpy_arr.reshape(3,3)
numpy_arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#converting a 1d array to 3d array
numpy_arr = np.array([x for x in range(1,13)])

In [20]:
numpy_arr_3d = numpy_arr.reshape(3,2,2)
numpy_arr_3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [21]:
#flatten method
numpy_arr_3d.reshape(-1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

conditional logic in numpyu arrays

In [22]:
x = np.array([x for x in range(1,10)])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.where(x%2==0,'even','odd')

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd'],
      dtype='<U4')

In [24]:
condlist = [x<5,x>5]
choicelist = [x**2,x**3]

In [25]:
np.select(condlist,choicelist,default=x)

array([  1,   4,   9,  16,   5, 216, 343, 512, 729])

indexing and slicing

In [26]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])


In [27]:
array_1d[-3]

4

In [28]:
array_2d[1,2]

6

In [29]:
array_3d[1,1,2]

12

slicing Part b

In [32]:
array_1d = np.array([1,2,3,4,5,6])
array_2d = np.array([[1,2,3],[4,5,6]])
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [33]:
array_1d

array([1, 2, 3, 4, 5, 6])

In [35]:
#array_1d[1:]
array_1d[3:5]

array([4, 5])

In [39]:
array_1d[-3:-1]

array([4, 5])

In [40]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
array_2d[1,1:]

array([5, 6])

In [43]:
array_2d[-2:-3:-1] 

array([[1, 2, 3]])